#! /bin/bash

# To use, set the CURRENT_PROGRAM environment variable.
# ex: export CURRENT_PROGRAM=2_add_two_numbers/add_two_numbers.c

echo "RUNNING: $CURRENT_PROGRAM"
gcc -O0 $CURRENT_PROGRAM && ./a.out
rm -f a.out
